# Site Build Settings
paginate: 5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Synaptic Transmissions'
description:	       'Central Latency Reduction'
author:              'Habakuk Hain'

theme: jekyll-theme-minimal
