# Site Build Settings
paginate: 5

# Collections
collections:
  questions:
    output: true
    permalink: /questions/:name/

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /posts/:categories-:slug/
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Synaptic Transmissions'
description:	       'Central Latency Reduction'
author:              'Habakuk Hain'

theme: jekyll-theme-minimal

# Post categories configuration
post_categories:
  transmission:
    title_prefix: "Transmission"
    description: "Brief transmissions from the neural frontier."
  dienstag:
    title_prefix: "Dienstag Dienst"
    description: "Weekly updates on findings that influence management of acute neurological conditions."
  radio_demo:
    title_prefix: "Radio-Demo"
    description: "Interesting neuroradiological cases and *blickdiagnoses*."
  conserved:
    title_prefix: "Conserved Feature"
    description: "Classical papers that are still relevant today."
  convergence:
    title_prefix: "Convergence"
    description: "Round-up of findings that did not fit anywhere else"
